### ISSUE TITLE
Comp return nodes have an unfixable error in `0.2.2`

### ISSUE THREAD

**Issue by mdegat01** [ollixx/node-red-contrib-components#45]
After updating to `0.2.2` any new comp return nodes I drop in have an unfixable error. You can see the error triangle on the nodes in this screenshot:
![Screen Shot 2021-12-08 at 10 29 47 AM](https://user-images.githubusercontent.com/2037026/145235757-7b57ceb1-ac35-4b7f-af84-66c976469148.png)

Nothing I change within the node's config seems to remove this error. The nodes actually work if I deploy and run the component but I get a warning every time I deploy now and there doesn't seem to be anything I can do to make it go away. Copying and pasting existing return nodes which don't have this warning doesn't work either, the new copies still have the error.

**Comment by ollixx** [comment]
I fixed that with 0.2.3. Please check that version and see, if it solves your problem, too.

**Comment by mdegat01** [comment]
Hm I'm still seeing it on 0.2.3
![Screen Shot 2021-12-08 at 11 19 43 AM](https://user-images.githubusercontent.com/2037026/145244199-93d229d0-24b8-4e98-86d4-d0d5792d3e74.png)
![Screen Shot 2021-12-08 at 11 20 29 AM](https://user-images.githubusercontent.com/2037026/145244285-ca904f5b-a9e6-49c8-8d5b-05a1919a4549.png)

**Comment by ollixx** [comment]
yes, sorry. That keeps me busy for a long time now. You can get rid of it just opening the node, saving it and deploy. It is a validation, that can only be done while saving the node's configuration in the editor. I have to find a better solution for that...

**Comment by mdegat01** [comment]
Ah I see what was happening. Since I was testing I had just dropped in a `component_in` node, a `component_out` node and a `component` node to use it all at the same time without deploying.

It looks like if you drop in a `component_out` node for a `component_in` node that you haven't deployed yet then you can't fix that `node_is_not_connected` error no matter how many times you open and close the config panel. But once the `component_in` node has been deployed then you just have to open up the config panel of the matching `component_out` and press done and the error goes away.

Sorry it's been a time sink, I didn't realize. Honestly if you just put a little note in the readme saying this workaround that would probably be good enough I think.

**Comment by ollixx** [comment]
It's important for me to get such feedback - I usually have very few. Of course I want the nodes to work as perfectly as possible. But since the nodes are strongly interconnected, it is not so easy to find the right way of validating the correct state at the right time. That is, because node-red is not designed to have such dependencies between nodes. So to validate the connections between them is really an advanced task and error prone.
But to see people using it gives me the drive to keep on working on it.
So thanks again for letting me know.
